version: 2
jobs:
   one:
     docker:
       - image: quay.io/azaka/ubuntu-user
         auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
     steps:
       - checkout
       - setup_remote_docker
       - run: echo "hello world"

workflows:
  version: 2
  wfone:
    jobs:
      - one
