version: 2
jobs:
   one:
     docker:
       - image: circleci/classic:201708-01
     steps:
       - checkout
       - setup_remote_docker
       - run: echo "hello world"

workflows:
  version: 2
  wfone:
    jobs:
      - one
