version: 2
jobs:
   one:
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker
       - run: echo "hello world"

workflows:
  version: 2
  wfone:
    jobs:
      - one
